<template>
  <div class="flex flex-col">
    <a
      m-2
      i-carbon:debug
      hover:text-amber
      rel="noreferrer"
      href="https://bbs.nga.cn/read.php?tid=30999435"
      target="_blank"
      title="报Bug"
    />
    <a
      m-2
      i-carbon:logo-github
      hover:text-amber
      rel="noreferrer"
      href="https://github.com/Waaatanuki/gbf-app"
      target="_blank"
      title="GitHub"
    />
  </div>
</template>
